#!/bin/bash

createdb -U postgres mapit
psql -U postgres -d mapit -c 'create extension postgis;'

echo 'MAPIT_DB_NAME: mapit' > conf/general.yml
echo 'MAPIT_DB_USER: postgres' >> conf/general.yml
echo 'DJANGO_SECRET_KEY: secret' >> conf/general.yml
echo 'COUNTRY: GB' >> conf/general.yml
