# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-05 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapit', '0002_auto_20141218_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codetype',
            name='code',
            field=models.CharField(help_text="A unique code, eg 'ons' or 'unit_id'", max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='nametype',
            name='code',
            field=models.CharField(help_text="A unique code to identify this type of name: eg 'english' or 'iso'", max_length=500, unique=True),
        ),
    ]
