# Generated by Django 3.2.18 on 2023-05-23 09:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('mapit', '0004_add_country_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeometrySubdivided',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', django.contrib.gis.db.models.fields.PolygonField(srid=settings.MAPIT_AREA_SRID)),
                ('geometry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivided', to='mapit.geometry')),
            ],
            options={
                'verbose_name_plural': 'subdivided geometries',
            },
        ),
    ]
