# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapit', '0004_add_country_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='geometry',
            name='areas',
            field=models.ManyToManyField(related_name='polygons', to='mapit.Area'),
        ),
        migrations.AlterField(
            model_name='geometry',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygons_old', to='mapit.Area', null=True),
        ),
    ]
