# Generated by Django 3.2.18 on 2023-05-23 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapit', '0005_geometrysubdivided'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""INSERT INTO mapit_geometrysubdivided (geometry_id, division)
                SELECT id,ST_Subdivide(polygon) FROM mapit_geometry""",
            reverse_sql="TRUNCATE mapit_geometrysubdivided RESTART IDENTITY"
        ),
    ]
