# Generated by Django 5.2.5 on 2026-01-15 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapit', '0006_auto_20230523_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codetype',
            options={'ordering': ('code',)},
        ),
        migrations.AlterModelOptions(
            name='nametype',
            options={'ordering': ('code',)},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ('code',)},
        ),
    ]
