# Generated by Django 3.2.9 on 2021-11-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapit_labour", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uprn",
            name="postcode",
            field=models.CharField(db_index=True, max_length=7),
        ),
    ]
