# Generated by Django 3.2.9 on 2021-11-04 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mapit", "0004_add_country_m2m"),
        ("mapit_labour", "0002_alter_uprn_postcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="Code",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=500)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uprn_codes",
                        to="mapit.codetype",
                    ),
                ),
                (
                    "uprn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codes",
                        to="mapit_labour.uprn",
                    ),
                ),
            ],
            options={
                "unique_together": {("uprn", "type")},
            },
        ),
    ]
