# Generated by Django 3.2.9 on 2021-11-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapit_labour", "0003_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="code",
            name="code",
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
